language: php

sudo: false

php:
  - 5.4
  - 5.5
  - 5.6

before_install:
  - composer install
  - composer require --prefer-source --dev squizlabs/php_codesniffer:~2.0
  - composer create-project --prefer-source -s dev --no-interaction cakephp/app tests/test_app
  - cp tests/Fixture/composer.json tests/test_app/.
  - cp tests/Fixture/Installer.php tests/test_app/src/Console/Installer.php
  - cd tests/test_app
  - composer require --prefer-source --dev cakephp/codeception:dev-$TRAVIS_BRANCH#$TRAVIS_COMMIT
  - rm composer.lock
  - composer install --prefer-source
  - vendor/bin/codecept bootstrap
  - vendor/bin/codecept generate:cest Functional Foo
  - vendor/bin/codecept generate:cept Functional Foo
  - cd ../sample_app
  - cp ../test_app/composer.json .
  - cp ../Fixture/Installer.php src/Console/.
  - composer install --prefer-source
  - vendor/bin/codecept build

script:
  - vendor/bin/codecept run && cd ../..
  - vendor/bin/phpcs --standard=PSR2 --extensions=php --ignore=tests/*_app src/ tests/
  - phpunit
